### ISSUE TITLE
Sketch not working

### ISSUE THREAD

**Issue by BertJager** [Apress/ESP8266-and-ESP32#1]
E:\Arduino\Sketches\Listing1_3_NEW.ino\Listing1_3_NEW.ino.ino:16:29: error: no matching function for call to 'VS1053::VS1053(int&, int&, int&)'
 VS1053 decoder(CS, DCS, DREQ);      // associate decoder with VS1053
                             ^
In file included from E:\Arduino\Sketches\Listing1_3_NEW.ino\Listing1_3_NEW.ino.ino:10:
e:\Arduino\Sketches\libraries\ESP32-vs1053_ext\src/vs1053_ext.h:299:5: note: candidate: 'VS1053::VS1053(uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t)'
     VS1053(uint8_t _cs_pin, uint8_t _dcs_pin, uint8_t _dreq_pin, uint8_t spi, uint8_t mosi, uint8_t miso, uint8_t sclk);
     ^~~~~~
e:\Arduino\Sketches\libraries\ESP32-vs1053_ext\src/vs1053_ext.h:299:5: note:   candidate expects 7 arguments, 3 provided
e:\Arduino\Sketches\libraries\ESP32-vs1053_ext\src/vs1053_ext.h:109:7: note: candidate: 'VS1053::VS1053(const VS1053&)'
 class VS1053 : private AudioBuffer{
       ^~~~~~
e:\Arduino\Sketches\libraries\ESP32-vs1053_ext\src/vs1053_ext.h:109:7: note:   candidate expects 1 argument, 3 provided
Multiple libraries were found for "SD.h"
  Used: C:\Users\jager\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\libraries\SD
  Not used: C:\Users\jager\AppData\Local\Arduino15\libraries\SD
exit status 1

Compilation error: no matching function for call to 'VS1053::VS1053(int&, int&, int&)'

**Comment by NDC-SC** [comment]
With an ESP32 microcontroller, Listing1-3_NEW compiled (19 Nov), with version 1.0.10 of the ESP32-vs1053_ext library
and the sketch downloaded from github.com/Apress/ESP8266-and-ESP32/tree/master/Chapter 1/Listing1-3_NEW

The instruction VS1053 decoder(CS, DCS, DREQ), which has three parameters, is equivalent to  VS1053 mp3(VS1053_CS, VS1053_DCS, VS1053_DREQ) in the vs1053_ext example in the library.

**Comment by NDC-SC** [comment]
The github.com/schreibfaul1/ESP32-vs1053_ext library was recently updated, but the library version is still 1.0.10.
One of the changes included the VSPI parameter and the SPI pins in the instruction:
VS1053 mp3(VS1053_CS, VS1053_DCS, VS1053_DREQ, VSPI, VS1053_MOSI, VS1053_MISO, VS1053_SCK);
which previously only required the first three parameters.
The ESP32 microcontroller hosts four SPI peripherals with SPI0 and SPI1 to access the flash memory, while SPI2 and SPI3 are general-purpose SPI controllers, referenced as HSPI and VSPI, respectively.

Using the pin layout from Table 1-1, the updated instructions in Listing 1-3 are:
int MOSIpin = 23;
int MISOpin = 19;
int SCKpin = 18;
int CS = 0;
int DCS = 2;            // define VS1053 decoder pins
int DREQ = 4;
VS1053 decoder(CS, DCS, DREQ, VSPI, MOSIpin, MISOpin, SCKpin);

In the setup function replace   SPI.begin();    with   SPI.begin(SCKpin, MISOpin, MOSIpin);
